### ISSUE TITLE
Extract shared/common parts

### ISSUE THREAD

**Issue by sonallux** [jvalue/ods#221] opened 2020-10-08 17:06 UTC
This issue is for discussing if it might be beneficial for the ODS to extract shared/common parts from the microservices, especially from the ones written in TypeScript. In general, removing duplication by extracting shared/common parts should improve the developer experience and lower the maintenance cost. 

Currently, all microservices are completely separated and a lot of things are duplicated. The duplications can be categorised by **code**, **tooling** and **schema**. Each category will need a different solution on how to extract shared/common parts. In the following, I will describe some examples for each category and different ideas for removing the duplication:

### Shared code
All those shared code fragments can be extracted to a shared library that **can** be used by the microservices.
- generic retry function
- sleep function from `sleep.ts`
- validators from `validators.ts`
- [AmqpPublisher](https://github.com/jvalue/open-data-service/blob/master/pipeline/src/pipeline-config/publisher/amqpPublisher.ts)
- [AmqpConsumer](https://github.com/jvalue/open-data-service/blob/master/storage/storage-mq/src/util/amqpConsumer.ts)
- database connection abstraction: [PostgresRepository](https://github.com/jvalue/open-data-service/blob/master/storage/storage-mq/src/util/postgresRepository.ts)

### Shared tooling
The linter config, the eslint and eslint-plugins dependency version are duplicated in every microservice. They can be moved to the root of the repository, so every microservice is using the same linter setup.

### Shared schemas
Currently, the schema of amqp messages and REST endpoints are duplicated at consumer and producer site. This will make adjusting the schema error-prone because an instance is easily missed. With a single shared ground of truth for the schemas of messages, the compiler can already detect issues with misaligned schemas. Those schemas can be put for example into an [OpenApi](https://www.openapis.org) or/and [AsyncApi](https://www.asyncapi.com) documentation. Then libraries for different programming languages can be generated automatically from those documentations.

---
#### Two words about monorepos
I think sticking with the current monorepo is a must if we want to extract things. But unfortunately `npm` does not support monorepos with shared libraries and dependencies. Therefore a tool like [lerna](https://lerna.js.org) or [Nx](https://github.com/nrwl/nx) is needed on top of `npm`.

**Comment by georg-schwarz** [comment] 2020-10-09 09:56
I think this discussion is strongly related to the question of how we want to evolve our architecture in the future. Currently, we have a shared-nothing approach between the microservices, which makes sense if we would have a system in production and want to maintain different service development life-cycles (independent deployment). This, however, does not fit the current mono-repo approach.

Including the current phase of our project (merely prototyping), the cost of having this shared-nothing approach overweights the benefits we might have in the future. So instead of sticking to the shared-nothing approach, I also suggest loosening this up and use.

I like your three categories, so let's discuss that independently.

# Shared Code

* We can share code for common functionality, but without including business logic in there. We could also publish really small npm packages and reuse them as a "normal" library. So we might get around the monorepo npm issue. That should work since these helpers shouldn't change too often. No strong need to keep them in sync in my opinion. One service could stick with the old version independently of the rest of the system.

# Shared tooling

* Currently we only have the linter as shared tooling, right? It is something that should also not change too frequently. Moving it up or down is no big effort, so we can reverse a decision here quite easily. If it is just the linter, we can go either way IMHO, both ways (keeping in sync manually or pulling up one level) seem to bear a certain effort, but not a huge one.

# Shared schemas

* I am still a little hesitant about that aspect. I think the root of the problem is, that the integration tests cannot cover the problem completly.
* OpenAPI can be used for our RESTful APIs, also to generate client code on the UI. I think that might be a good idea to investigate that further.
* AsyncAPI seems to be too unstable. I found no official generator for typescript code, unfortunately.
* The usual approach with microservices on that issue are Consumer-Driven Contract Tests. [Pact.js](https://github.com/pact-foundation/pact-js) is an example library for that. Maybe we can also tackle the problem like this?
* Not sharing the API models (which change most frequently at the current project state) would save us the mentioned monorepo issue with `npm`

**Comment by georg-schwarz** [comment] 2020-11-16 15:15
Started extracting non-business-logic code into libraries in #243 

What I plan is doing additional libs (building on the basics) for
* postgres access
* amqp consuming / producing

What we also might do: publish our own eslint config and reuse it.

What do you think of that approach? @jsone-studios @lunedis @mathiaszinnen @MBuchalik

**Comment by MBuchalik** [comment] 2020-11-16 17:06
I unfortunately haven't worked enough with these parts of the ODS to provide a solid answer.

But in general, I really like the approach of moving commonly used stuff into own packages. You just have to be careful when changing something in the packages. Maybe, use semver and always try to minimize the number of major releases.

Regarding the eslint config: So the locally used `.eslintrc.js` would then look like this?
```js
module.exports = {
  extends: '@jvalue/eslint-something',
  parserOptions: {...},
}
```

It would be nice if it was possible to have multiple configs (e.g. one for vue). So that you can say

```js
module.exports = {
  extends: ['@jvalue/eslint-basic', '@jvalue/eslint-vue'],
  parserOptions: {...},
}
```


One downside of this overall approach of shared config files is that it becomes harder and harder to extend the linter. So this decision really needs to be thought out carefully.

**Comment by georg-schwarz** [comment] 2020-11-17 07:56
Yeah I don't think these things should change too often. The good thing with semantic versioning and publishing the package is that each microservice can upgrade independently. If we have multiple versions in the overall system it should bot break things. This means of course not putting in there stuff that lets counterparts break!

Regarding the linter @MBuchalik 
That's exactly what I would expect it to look like. Then every project has the possibility to make adaptions if necessary and if we find them useful we can pull them up into the published one. Same thoughts on semantic versioning apply here I guess.

**Comment by georg-schwarz** [comment] 2020-12-09 09:19
# Update

We extracted shared code into libraries
* [amqp](https://github.com/jvalue/node-dry-amqp) consumer and producer
* [postgres](https://github.com/jvalue/node-dry-pg) repository
* [basics](https://github.com/jvalue/node-dry-basics): sleep, validators, env reading, sleep

**Comment by georg-schwarz** [comment] 2020-12-09 09:20
Next up: eslint config?

I'd still refrain from sharing model classes!

**Comment by sonallux** [comment] 2020-12-09 09:54
> Next up: eslint config?

I think it is not worth the effort doing that now because we already use the shared ESLint config from StandardJS (e.g. [eslint-config-standard-with-typescript](https://github.com/standard/eslint-config-standard-with-typescript) for TS and [eslint-config-standard](https://github.com/standard/eslint-config-standard) for JS). Our `.eslintrc` files are only about 25 loc so the saving would be marginal.

Another thing is that all the external plugins used by a shared ESLint config, must still be specified as dependencies in our `package.json`. This is due to a [known limitation in ESLint](https://github.com/eslint/eslint/issues/3458). That's also the reason why we currently have all the eslint plugins as dependencies in our `package.json` files, but do not reference them in our `.eslintrc` files.

There are a lot of workarounds mentioned in the ESLint issue, but I do not have tried any of them and I think doing so is not worth the effort. The ESLint team is working on a [new simplified configuration file format](https://github.com/eslint/eslint/issues/13481), that will solve the above-mentioned issue. But that will not be ready in the near future.

**Closed as completed** 2021-01-21 10:58 UTC
